#!/usr/bin/python3
# SPDX-License-Identifier: 2.0 license with LLVM exceptions

import argparse
from lib.utils.git import get_repo_info, download_beman_standard
from lib.pipeline import run_checks_pipeline

def parse_args():
    """
    Parse the command line arguments.
    """

    parser = argparse.ArgumentParser()
    parser.add_argument("--repo_path", help="path to the repository to check",
                        required=True)
    parser.add_argument("--fix_inplace", help="try to automatically fix found issues",
                        action=argparse.BooleanOptionalAction, default=False)
    parser.add_argument("--coverage", help="show coverage of the checks",
                        action=argparse.BooleanOptionalAction, default=False)
    args = parser.parse_args()

    # Get repository information
    repo_info = get_repo_info(args.repo_path)
    args.prepo_pathath = None
    args.repo_info = repo_info

    return args


def main():
    """
    beman-tidy main entry point.
    """
    args = parse_args()

    beman_standard = download_beman_standard()
    run_checks_pipeline(args.repo_info, beman_standard, fix_inplace=args.fix_inplace, coverage=args.coverage)

if __name__ == "__main__":
    main()
